### ISSUE TITLE
Group steps missing "commands"

### ISSUE THREAD

**Issue by chomey** [buildkite/docs#1256]
Per https://buildkite.com/docs/pipelines/group-step#parallel-groups
The example shows:
```
steps:
  - group: "111"
    depends_on: "tests"
    steps:
      - command: "a.sh"
      - wait
      - command: "b.sh"
```

To be in line with the rest of the buildkite pipelines, can support for `commands` be added and not just `command`?

Expected:
```
steps:
  - group: "111"
    depends_on: "tests"
    steps:
      - commands: 
         - "a.sh"
         - wait
         - "b.sh"
```
