### ISSUE TITLE
Fixed state does not exists

### ISSUE THREAD

**Issue by Thiryn** [buildkite/docs#1329]
https://github.com/buildkite/docs/blob/22bacc56506e3827c4b92e1126e4b917c7bb4a5c/pages/pipelines/conditionals.md.erb#L269

Hi, I am following this doc and it seems like the `fixed` state does not exist. Looking through other parts of the doc, it seems like this state indeed does not exists.
Getting the following error when building

> invalid: `if` expression failed to parse: "fixed" is not a valid `build.state` — did you mean "failed"?

**Comment by GMNGeoffrey** [comment]
Hello there. I am hitting this same error when trying to use this state in a notify step. 

The link for notification services in the docs is https://buildkite.com/docs/pipelines/notifications#conditional-notifications and I believe I am using the variable exactly as specified there, but am getting an error.


```yaml
notify:
  - email: "llvm-bazel-alerts@googlegroups.com"
    if: build.state == "failed" || build.state == "fixed"
```

![image](https://user-images.githubusercontent.com/5732088/159099468-22b5aefe-8076-43b1-9ebd-21d8f1920d1a.png)

Does this only work with external integrations for some reason?
