### ISSUE TITLE
`email` is not a valid step notification type

### ISSUE THREAD

**Issue by keoma-di** [buildkite/docs#1724]
I'd like to receive notifications on one of our pipelines. I'm testing the most basic configuration the docs describe, but I'm getting the folllowing error:

```


export DOCKER_VERSION=19.03.13
--
  | export BUILDKITE_STACK_NAME=buildkite
  | export BUILDKITE_STACK_VERSION=v5.1.0
  | export BUILDKITE_AGENTS_PER_INSTANCE=1
  | export BUILDKITE_SECRETS_BUCKET=buildkite-managedsecretsbucket-1h6eph6la8bte
  | export AWS_DEFAULT_REGION=ap-southeast-2



2022-09-07 06:58:54 WARN   POST https://agent.buildkite.com/v3/jobs/018316be-55b6-4759-a00a-XXXXXXXXXX/pipelines: 422 `email` is not a valid step notification type (Attempt 1/60 Retrying in 5s)
--
  | 2022-09-07 06:58:54 ERROR  Unrecoverable error, skipping retries
  | 2022-09-07 06:58:54 FATAL  Failed to upload and process pipeline: POST https://agent.buildkite.com/v3/jobs/018316be-55b6-4759-a00a-XXXXXXXXXXXXXX/pipelines: 422 `email` is not a valid step notification type
  | 🚨 Error: The command exited with status 1
```
This is my step:
```
steps:
  - name: "mystep"
    branches: master
    command: ./mycmd.sh
    notify:
      - email: "my@email.com"
    env:
      AWS_ROLE_ARN: "${ROLE}"
```

**Comment by plaindocs** [comment]
Hi @keoma-di 

`notify` is at the same level as `steps` so something like this should work. 

```
steps:
  - name: "mystep"
    branches: master
    command: ./mycmd.sh
notify:
  - email: "my@email.com"
env:
  AWS_ROLE_ARN: "${ROLE}"
```

You can also configure notifications for `group` steps https://buildkite.com/docs/pipelines/group-step#group-step-attributes

Let me know if that doesn't work for you, or if there was anything you found particularly unclear. I'll add a `steps` key to the examples in https://buildkite.com/docs/pipelines/notifications#email to clarify this.
