### ISSUE TITLE
Matrix support for plugins

### ISSUE THREAD

**Issue by vchuravy** [buildkite/docs#1865]
Currently the docs state:

> You can't use matrix values in other attributes, including step keys and plugin attributes.

https://buildkite.com/docs/pipelines/build-matrix

For plugins this would be incredibly helpful. As an example we have the `julia` plugin that takes a version attribute.

```
steps:
  - label: "CUDA Julia v{{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.6"
          - "1.7"
          - "1.8"
          - "nightly"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
```

Right now I either have to duplicate the CI definition or not use the plugin...

**Comment by vchuravy** [comment]
For anyone looking for a interim solution, since plugin attributes are just environment variables one can use the environment to set the attribute.

```
    matrix:
      setup:
        version:
          - "1.6"
          - "1.7"
          - "1.8"
          - "nightly"
    env:
      BUILDKITE_PLUGIN_JULIA_VERSION: "{{matrix.version}}"
    plugins:
      - JuliaCI/julia#v1: ~
```
