### ISSUE TITLE
Block and wait behaving unexpectedly

### ISSUE THREAD

**Issue by stephwestgarth** [buildkite/docs#2634]
Hi team!

Not 100% sure both are an issue with buildkite itself, but we've seen a change in behaviour recently that feels like a bug.

For some context, our pipeline looks a bit like this (majorly simplified):

- Install FE dependencies
- Install BE dependencies
- Build FE (if installing passes)
- Linting (if install steps pass)
- Tests (if install steps pass, these are a whole bunch of concurrent tasks that wait on the install/build steps relevant to them, aka FE or BE)
- Upload metrics (no dependency, only on main branch)

On dev branches, we have a block step at the end to optionally spin up a webapp we can use for review, and on production, there's no block/review app step and instead a wait step that then triggers the deploy to production when everything passes. They are declared in this order in our pipeline.yml file, with conditionals on the block/wait steps and resulting actions to say which branches they should be present on.

A little while ago, the block step could run independently of the tests (it's a test app, we don't care if tests have passed in this case). This stopped at some point (we're not sure when) and so we've manually added a "depend_on: ~" to get this working again.

However, by doing that, the wait step (which is only present on our main branch, based on a conditional in the file) no longer waits, which makes no sense. Are the docs misleading or have we found a bug?

**Comment by mcncl** [comment]
For any future travelers, the ordering of the `wait` and `block` is important; where a conditional is used on a `block`, the `wait` should precede it in order for it to not also be dependent on the conditional.

```yaml
steps:
  - label: Hello, world! 👋
    command: |
      echo "Hello, world!"
  - wait: ~
  - if: time == "night"
    block: Say goodnight! 🥱
  - label: Bed time 🛌
    command: |
      echo "Goodnight, world!"
```

In the above, the `wait` is still present no matter the conditional result, so we don't ignore it.  However, in the following it would be ignored:

```yaml
steps:
  - label: Hello, world! 👋
    command: |
      echo "Hello, world!"
  - if: time == "night"
    block: Say goodnight! 🥱
  - wait: ~ 
  - label: Bed time 🛌
    command: |
      echo "Goodnight, world!"
```

The above `wait` is dependent on the presence of the `block`, which is dependent on the conditional being met. Because at upload time we cannot guarantee that the conditional is met or unmet, we cannot determine if the `wait` will be required, so it's ignored.

We have more documentation on using `wait` steps with `block` steps [here](https://buildkite.com/docs/pipelines/wait-step#block-steps-interacting-with-wait-steps).
