### ISSUE TITLE
Github short plugin sources don't work

### ISSUE THREAD

**Issue by jam13** [buildkite/docs#265]
Docs say that `foo/bar#v1.0` will refer to a github repo at https://github.com/foo/bar-buildkite-plugin (https://buildkite.com/docs/agent/v3/plugins#plugin-sources). This appears not to be true, instead it is trying to use a URL of https://foo/bar

**Comment by toolmantim** [comment]
Thanks for the report! That definitely sounds like a bug though.

I've just done some tests here, and I can't seem to replicate it with buildkite-agent v3.2.0:

* https://github.com/toolmantim/test-buildkite-plugin
* https://gist.github.com/toolmantim/6dab441efa06292d21e946d15e1e4b78

![image](https://user-images.githubusercontent.com/153/41270529-24b41326-6e4f-11e8-9e79-dc7cb6942f04.png)

Can you share the pipeline.yml you're using? And what version of the buildkite-agent? If you'd like to email support@buildkite.com, that also might be a better place.

**Comment by jam13** [comment]
Sorry for the terse bug report, I should have been more accurate.

The exact pipeline step I was using was:
```
- label: ":ecs: :rocket: Deploy"
  plugins:
    healthefrog/ecs-deploy#feature/fix_task_definition:
      cluster: "${ECS_CLUSTER}"
      service: "${ECS_SERVICE}"
      task-definition: "./task-definition.json"
      task-family: "${ECS_TASK_DEFINITION}"
      image: "${REPOSITORY_URI}:${BUILDKITE_BUILD_NUMBER}"
```

and I am using linux agent v3.2.0.

I didn't attempt to debug it as I was in a hurry and it was not a problem to just use the long form syntax, but I wonder whether the slash in the branch name be the issue.
