### ISSUE TITLE
Buildkite plugin step

### ISSUE THREAD

**Issue by joscha** [buildkite/docs#275]
Would it be possible to get some more docs around **https://buildkite.com/docs/agent/v3/plugins**, please?

E.g. can standalone plugin-steps target specific agents?

**Comment by lox** [comment]
Howdy! Do you mean something like:

```yaml
steps:
  - plugins:
       detect-clowns#v2.0.0: ~
       agents:
         queue: 'clown-infrastructure'
```
