### ISSUE TITLE
Allow to select multiple options in select input

### ISSUE THREAD

**Issue by davidsevcik** [buildkite/docs#365]
Hello,

would be possible to extend select input in pipeline to support selection of multiple options at the same time or alternatively add checkbox input? 

We currently use text input as a workaround:
```
  - block: ":rocket: Deploy to production! :dragon:"
    branches: "master"
    fields:
      - text: "Which components you want to deploy?"
        key: "components"
        required: true
        default: "admin platform-api-v4 rw-api workers cronjobs"
```

Thanks.
