### ISSUE TITLE
Mixing depends_on and block/wait doesn't work as expected.

### ISSUE THREAD

**Issue by mboudreau** [buildkite/docs#714]
Let's say I have the following steps:

```
steps:
  - command: yarn build
    key: build
    artifact_paths: dist/**/*
  
  - command: yarn lint
    key: lint
    
  - command: yarn test
    key: test
    
  - block
    
  - depends_on: build
    command:
      - buildkite-agent artifact download 'dist/*' .
      - yarn integration-tests
```

Now, when I read this I assume that the last step that depends on the build but is after the block would mean that this step doesn't run unless 2 dependencies are met: that the step above is unblocked and that the build step finished. However this is not the case in practicality.

From my observation, `block`/`wait` does not mix with `depends_on`, which is frustrating to say the least.  What I've seen is that once the build command is done, any commands that has a `depends_on: build` gets run right after, completely ignoring a `block` or `wait` command before it.  I find this unacceptable.  

Regardless of my opinion, I was confused as to why this is never mentioned in the documentation.  This scenario caused a production deployment when it shouldn't have happened as it should have been blocked;  we were lucky that the deployment didn't affect our current users.

**Comment by plaindocs** [comment]
Hi @mboudreau 

Thanks for pointing this out. I've run a few tests which confirm that `depends_on` does bypass the `block`. I'll find out if this is intended behavior or a bug, and get the docs updated either way.

In the meantime, I think making the `block` step have the dependency does what you intend?

```yaml
steps:
  - command: yarn build
    key: build
    artifact_paths: dist/**/*
  
  - command: yarn lint
    key: lint
    
  - command: yarn test
    key: test
    
  - block
    depends_on: build
  
  -  command:
      - buildkite-agent artifact download 'dist/*' .
      - yarn integration-tests
```
